i18n/en-US/guides/ALaCarte.js
i18n/en-US/guides/index.js
pages/guides/ALaCartePage.vue

Essentially, this is the most important part:
It is a list in which you can search by name of the markup or by name of the import, and you can select with the checkbox the components you want, and to end if we click on the button with the copy icon in the bottom left, We copy the formatted components ready to paste in our project.
Adrià.

Added a-la-carte simple guide with list of component and automatic generator ready to easily copy the selected elements

---

examples/pickers/dateIcons.vue
examples/pickers/monthIcons.vue
i18n/en-US/components/Pickers.js

docs for https://github.com/vuetifyjs/vuetify/pull/2709

picker icons

---

assets/App.vue
router/scroll-behavior.js

fix anchor scroll

---

examples/grid/offset.vue

fixing grid offset example not displaying as expected with the given labels

---

examples/selection-controls/checkboxesInlineTexfield.vue
i18n/en-US/components/SelectionControls.js

add inline checkbox example

---

api/api.js
components/helpers/Parameters.vue
components/views/ExampleView.vue
lang/en/components/DataTables.js
lang/en/generic/Pages.js
lang/en/mixins/DataIterable.js

re-designed API section
https://i.imgur.com/RHKmFFU.png

re-designed API section

---

lang/zh_Hans/components/Cards.js
lang/zh_Hans/components/Carousels.js
lang/zh_Hans/components/Chips.js
lang/zh_Hans/components/Toolbars.js

There are many pages  had not been translated yet. 😆

Chinese Translation for Components Pages

---

lang/zhHans/components/DataTables.js
lang/zhHans/components/Dialogs.js
lang/zhHans/components/FloatingActionButtons.js
lang/zhHans/components/Footer.js
lang/zhHans/components/Lists.js
lang/zhHans/components/SelectionControls.js
lang/zhHans/components/Selects.js
lang/zhHans/components/Steppers.js
lang/zhHans/components/TextFields.js
lang/zhHans/mixins/DataIterable.js

[ i18n_zh-Hans ] Translation.

---

examples/data-tables/crud.vue

fixes #229
added confirm on delete
editing item and closing without saving doesn't change the item in table

fixed crud example

---

examples/data-tables/crud.vue
examples/data-tables/editdialog.vue
examples/data-tables/expand.vue
examples/data-tables/footer.vue
examples/data-tables/headerCell.vue
examples/data-tables/headerless.vue
examples/data-tables/headers.vue
examples/data-tables/noData.vue
examples/data-tables/pageText.vue
examples/data-tables/paginate.vue
examples/data-tables/progress.vue
examples/data-tables/search.vue
examples/data-tables/select.vue
examples/data-tables/server.vue
examples/data-tables/sort.vue
examples/data-tables/standard.vue

decrease number of columns in data tables

---

assets/App.vue
components/views/DocView.vue
lang/en/meta.js
pages/store/LicensingPage.vue
router/paths.js

Add licensing page for store products

---

examples/date-pickers/dateLight.vue
lang/en/components/DatePickers.js
lang/ko/components/DatePickers.js
lang/ru/components/DatePickers.js

date picker reactive prop

---

examples/data-tables/customIcons.vue
lang/en/components/DataTables.js
lang/ko/components/DataTables.js
lang/ru/components/DataTables.js
lang/zhHans/components/DataTables.js

data table custom icons

---

examples/data-tables/editdialog.vue
lang/en/components/DataTables.js
lang/ko/components/DataTables.js
lang/ru/components/DataTables.js
lang/zhHans/components/DataTables.js

https://github.com/vuetifyjs/vuetify/pull/3196

**persistent** prop for v-edit-dialog

---

lang/ru/vuetify/Home.js

RU lang fix: becomingAPatron

---

lang/ru/style/Colors.js

remove spaces and fix grammar

---

.travis.yml
now.json
package.json

feat(deployment): added automatic ci deployment

---

components/misc/SupportVuetify.vue

Fixes cropped patreon button with use of flexbox to make it mobile responsive. 
fixes #306
Desktop Widths:
Mobile:

Fix: cropped patreon banner

---

lang/en/layout/Spacing.js

Added the missing option 'a' for the spacing classes

Added 'a' option for the spacing classes

---

lang/ja/components/Icons.js

Japanese translation for Components/Icon

Japanese translation for Components/Icon

---

assets/App.vue

Changes app's snackbar to promote last few days remaining of tshirt giveaway.

chore: change app snackbar text

---

pages/store/ProductPage.vue

* Related to [#1561](https://github.com/vuetifyjs/vuetify/issues/1561)
* Fix relatted to PR [#3738](https://github.com/vuetifyjs/vuetify/pull/3738)
* Start working on adding prefix to classes [#1561](https://github.com/vuetifyjs/vuetify/issues/1561)
* Visually

Refactor (VCarousel): Add v- prefix to carousel classes

---

api/api.js
examples/menus/absolute.vue

* Related to [#1561](https://github.com/vuetifyjs/vuetify/issues/1561)
* Fix relatted to PR [#3740](https://github.com/vuetifyjs/vuetify/pull/3740)
* Start working on adding prefix to classes [#1561](https://github.com/vuetifyjs/vuetify/issues/1561)
* Visually

Refactor (VMenu): Add v- prefix to menu classes

---

examples/progress/circularColored.vue
examples/progress/circularDefault.vue
examples/progress/circularIndeterminate.vue
examples/progress/circularRotate.vue
examples/progress/circularSizeAndWidth.vue

* Related to [#1561](https://github.com/vuetifyjs/vuetify/issues/1561)
* Fix relatted to PR [#3740](https://github.com/vuetifyjs/vuetify/pull/3740)
* Start working on adding prefix to classes [#1561](https://github.com/vuetifyjs/vuetify/issues/1561)
* Not tested Wait for PR #3896 on vuetify repo to be merged

Refactor (VProgressCircular): Add v- prefix to progress-ciruclar classes

---

components/core/AppDrawer.vue
components/helpers/Example.vue
examples/layouts/googleKeep.vue
pages/ThemeGeneratorPage.vue

* Related to [#1561](https://github.com/vuetifyjs/vuetify/issues/1561)
* Fix relatted to PR [#3740](https://github.com/vuetifyjs/vuetify/pull/3740)
* Start working on adding prefix to classes [#1561](https://github.com/vuetifyjs/vuetify/issues/1561)
* Not tested  PR vuetifyjs/vuetify#3886 on vuetify repo not merged yet

Refactor (VNavigationDrawer): Add v- prefix to navigation-drawer classes

---

assets/index.template.html
package.json
static/manifest.json

- Tested manifest file loading in chrome developer tool and in Android 8.1 phone (Fix #410)
- Added cross-env in package.json
Note : We may want to add more icons for android and splash screen.

Updated and loading manifest.json

---

components/views/ExampleView.vue

Fixed misnamed property

---

lang/en/style/Theme.js
pages/ThemeGeneratorPage.vue
pages/style/ThemePage.vue

Just getting my feet wet.
* Added a new `Theme generator` section inside `Theme`.
* We have a working `back` button now inside the tool.
Thoughts?

Basic changes to the Theme Generator tool

---

src/data/components.json
src/examples/selects/selectionAppearance.vue
src/lang/en/components/Selects.json

feat(v-select) add: selection slot example 

---

src/lang/en/getting-started/FrequentlyAskedQuestions.json
src/pages/getting-started/FrequentlyAskedQuestionsPage.vue

Add Vue-CLI 3 config for assets relative paths resolution in custom Vuetify components.

Add Vue-CLI 3 config for relative paths resolution

---

src/examples/time-pickers/timeDialogAndMenu.vue

https://github.com/vuetifyjs/vuetify/pull/4905

fix: updated time picker in menu/dialog

---

lang/pt-br/components/FloatingActionButtons.js
lang/pt-br/generic/Common.js
lang/pt-br/vuetify/AppDrawer.js

I fixed some wrong translations and I translated the Floating Action Button component.

Translation pt br

---

src/data/layout/app-drawer-items.js

Inputs & controls was out of order

Menu items alphabetical order

---

src/data/components.json
src/data/deprecatedIn.json
src/data/newIn.json
src/examples/breadcrumbs/iconDividers.vue
src/examples/breadcrumbs/itemSlot.vue
src/lang/en/components/Breadcrumbs.json

https://github.com/vuetifyjs/vuetify/pull/4589

fix: update v-breadcrumbs examples and doc test
